import type { CareRecord } from "./model";

export const mockCareRecords: CareRecord[] = [
  {
    id: "record-1",
    patientId: "1",
    recordType: "blood_pressure",
    occurredAt: "2026-04-15T09:15:00+08:00",
    notes: "测量前静息 5 分钟，状态平稳。",
    source: "manual",
    metrics: [
      { key: "bloodPressureSystolic", value: 130, unit: "mmHg" },
      { key: "bloodPressureDiastolic", value: 85, unit: "mmHg" },
    ],
  },
  {
    id: "record-2",
    patientId: "1",
    recordType: "medication",
    occurredAt: "2026-04-15T08:00:00+08:00",
    notes: "已完成晨间用药。",
    source: "manual",
    metrics: [
      { key: "medicationName", value: "降压药" },
      { key: "medicationDose", value: "1片" },
    ],
  },
  {
    id: "record-3",
    patientId: "1",
    recordType: "heart_rate",
    occurredAt: "2026-04-14T20:00:00+08:00",
    notes: "睡前监测心率，节律平稳。",
    source: "ai",
    metrics: [{ key: "heartRate", value: 72, unit: "bpm" }],
  },
  {
    id: "record-4",
    patientId: "2",
    recordType: "blood_sugar",
    occurredAt: "2026-04-15T07:30:00+08:00",
    notes: "空腹血糖记录。",
    source: "manual",
    metrics: [{ key: "bloodSugar", value: 6.2, unit: "mmol/L" }],
  },
  {
    id: "record-5",
    patientId: "2",
    recordType: "diet",
    occurredAt: "2026-04-14T12:15:00+08:00",
    notes: "午餐完成情况良好。",
    source: "ai",
    metrics: [{ key: "dietDescription", value: "半碗米饭、清蒸鱼、炒青菜" }],
  },
  {
    id: "record-6",
    patientId: "3",
    recordType: "temperature",
    occurredAt: "2026-04-14T20:00:00+08:00",
    notes: "体征平稳。",
    source: "manual",
    metrics: [{ key: "temperature", value: 36.5, unit: "°C" }],
  },
  {
    id: "record-7",
    patientId: "3",
    recordType: "other",
    occurredAt: "2026-04-13T09:30:00+08:00",
    notes: "训练后精神状态良好。",
    source: "ai",
    metrics: [{ key: "observationText", value: "晨练后轻微疲劳，休息后恢复。" }],
  },
];
