import type { CareTask } from "./model";

export const mockCareTasks: CareTask[] = [
  {
    id: "task-1",
    patientId: "1",
    title: "测量血压",
    description: "晨间静息后记录收缩压和舒张压。",
    taskType: "blood_pressure",
    remindTime: "2026-04-15T09:00:00+08:00",
    repeatRule: "daily",
    priority: "normal",
    remindOffsetMinutes: 15,
    status: "completed",
  },
  {
    id: "task-2",
    patientId: "2",
    title: "服药提醒",
    description: "提醒餐后服用降糖药，并确认已完成。",
    taskType: "medication",
    remindTime: "2026-04-15T10:30:00+08:00",
    repeatRule: "daily",
    priority: "high",
    remindOffsetMinutes: 30,
    status: "pending",
  },
  {
    id: "task-3",
    patientId: "3",
    title: "康复训练",
    description: "完成今日上肢康复训练并观察疲劳反馈。",
    taskType: "rehab",
    remindTime: "2026-04-15T14:00:00+08:00",
    repeatRule: "daily",
    priority: "normal",
    remindOffsetMinutes: 15,
    status: "pending",
  },
  {
    id: "task-4",
    patientId: "1",
    title: "血糖检测",
    description: "记录午后血糖，保持与昨日同一时段。",
    taskType: "blood_sugar",
    remindTime: "2026-04-15T16:00:00+08:00",
    repeatRule: "daily",
    priority: "high",
    remindOffsetMinutes: 30,
    status: "pending",
  },
  {
    id: "task-5",
    patientId: "1",
    title: "复诊预约",
    description: "提醒准备近一周血压记录并按时复诊。",
    taskType: "appointment",
    remindTime: "2026-04-16T09:00:00+08:00",
    repeatRule: "once",
    priority: "normal",
    remindOffsetMinutes: 1440,
    status: "scheduled",
  },
  {
    id: "task-6",
    patientId: "3",
    title: "营养评估",
    description: "本周复盘饮食结构和体力恢复情况。",
    taskType: "nutrition",
    remindTime: "2026-04-17T10:00:00+08:00",
    repeatRule: "weekly",
    priority: "normal",
    remindOffsetMinutes: 60,
    status: "scheduled",
  },
];
